// Code generated by protoc-gen-go. DO NOT EDIT.
// source: factory.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FactoryGetPropertiesRq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FactoryGetPropertiesRq) Reset()         { *m = FactoryGetPropertiesRq{} }
func (m *FactoryGetPropertiesRq) String() string { return proto.CompactTextString(m) }
func (*FactoryGetPropertiesRq) ProtoMessage()    {}
func (*FactoryGetPropertiesRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7480700f1dd5ca1, []int{0}
}

func (m *FactoryGetPropertiesRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactoryGetPropertiesRq.Unmarshal(m, b)
}
func (m *FactoryGetPropertiesRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactoryGetPropertiesRq.Marshal(b, m, deterministic)
}
func (m *FactoryGetPropertiesRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactoryGetPropertiesRq.Merge(m, src)
}
func (m *FactoryGetPropertiesRq) XXX_Size() int {
	return xxx_messageInfo_FactoryGetPropertiesRq.Size(m)
}
func (m *FactoryGetPropertiesRq) XXX_DiscardUnknown() {
	xxx_messageInfo_FactoryGetPropertiesRq.DiscardUnknown(m)
}

var xxx_messageInfo_FactoryGetPropertiesRq proto.InternalMessageInfo

func (m *FactoryGetPropertiesRq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type FactoryGetPropertiesRs struct {
	Key               string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Subject           string `protobuf:"bytes,3,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Description       string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	ContextDataSchema string `protobuf:"bytes,5,opt,name=ContextDataSchema,proto3" json:"ContextDataSchema,omitempty"`
	ResultDataSchema  string `protobuf:"bytes,6,opt,name=ResultDataSchema,proto3" json:"ResultDataSchema,omitempty"`
	// use timestamp to represent
	Expiration           int64    `protobuf:"varint,7,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FactoryGetPropertiesRs) Reset()         { *m = FactoryGetPropertiesRs{} }
func (m *FactoryGetPropertiesRs) String() string { return proto.CompactTextString(m) }
func (*FactoryGetPropertiesRs) ProtoMessage()    {}
func (*FactoryGetPropertiesRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7480700f1dd5ca1, []int{1}
}

func (m *FactoryGetPropertiesRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactoryGetPropertiesRs.Unmarshal(m, b)
}
func (m *FactoryGetPropertiesRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactoryGetPropertiesRs.Marshal(b, m, deterministic)
}
func (m *FactoryGetPropertiesRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactoryGetPropertiesRs.Merge(m, src)
}
func (m *FactoryGetPropertiesRs) XXX_Size() int {
	return xxx_messageInfo_FactoryGetPropertiesRs.Size(m)
}
func (m *FactoryGetPropertiesRs) XXX_DiscardUnknown() {
	xxx_messageInfo_FactoryGetPropertiesRs.DiscardUnknown(m)
}

var xxx_messageInfo_FactoryGetPropertiesRs proto.InternalMessageInfo

func (m *FactoryGetPropertiesRs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FactoryGetPropertiesRs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FactoryGetPropertiesRs) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *FactoryGetPropertiesRs) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FactoryGetPropertiesRs) GetContextDataSchema() string {
	if m != nil {
		return m.ContextDataSchema
	}
	return ""
}

func (m *FactoryGetPropertiesRs) GetResultDataSchema() string {
	if m != nil {
		return m.ResultDataSchema
	}
	return ""
}

func (m *FactoryGetPropertiesRs) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type FactoryCreateInstanceRq struct {
	StartImmediately bool   `protobuf:"varint,1,opt,name=StartImmediately,proto3" json:"StartImmediately,omitempty"`
	ObserverKey      string `protobuf:"bytes,2,opt,name=ObserverKey,proto3" json:"ObserverKey,omitempty"`
	Name             string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Subject          string `protobuf:"bytes,4,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Description      string `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	// encoded as json
	ContextData          string   `protobuf:"bytes,6,opt,name=ContextData,proto3" json:"ContextData,omitempty"`
	FactoryKey           string   `protobuf:"bytes,8,opt,name=FactoryKey,proto3" json:"FactoryKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FactoryCreateInstanceRq) Reset()         { *m = FactoryCreateInstanceRq{} }
func (m *FactoryCreateInstanceRq) String() string { return proto.CompactTextString(m) }
func (*FactoryCreateInstanceRq) ProtoMessage()    {}
func (*FactoryCreateInstanceRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7480700f1dd5ca1, []int{2}
}

func (m *FactoryCreateInstanceRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactoryCreateInstanceRq.Unmarshal(m, b)
}
func (m *FactoryCreateInstanceRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactoryCreateInstanceRq.Marshal(b, m, deterministic)
}
func (m *FactoryCreateInstanceRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactoryCreateInstanceRq.Merge(m, src)
}
func (m *FactoryCreateInstanceRq) XXX_Size() int {
	return xxx_messageInfo_FactoryCreateInstanceRq.Size(m)
}
func (m *FactoryCreateInstanceRq) XXX_DiscardUnknown() {
	xxx_messageInfo_FactoryCreateInstanceRq.DiscardUnknown(m)
}

var xxx_messageInfo_FactoryCreateInstanceRq proto.InternalMessageInfo

func (m *FactoryCreateInstanceRq) GetStartImmediately() bool {
	if m != nil {
		return m.StartImmediately
	}
	return false
}

func (m *FactoryCreateInstanceRq) GetObserverKey() string {
	if m != nil {
		return m.ObserverKey
	}
	return ""
}

func (m *FactoryCreateInstanceRq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FactoryCreateInstanceRq) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *FactoryCreateInstanceRq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FactoryCreateInstanceRq) GetContextData() string {
	if m != nil {
		return m.ContextData
	}
	return ""
}

func (m *FactoryCreateInstanceRq) GetFactoryKey() string {
	if m != nil {
		return m.FactoryKey
	}
	return ""
}

type FactoryCreateInstanceRs struct {
	InstanceKey          string   `protobuf:"bytes,1,opt,name=InstanceKey,proto3" json:"InstanceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FactoryCreateInstanceRs) Reset()         { *m = FactoryCreateInstanceRs{} }
func (m *FactoryCreateInstanceRs) String() string { return proto.CompactTextString(m) }
func (*FactoryCreateInstanceRs) ProtoMessage()    {}
func (*FactoryCreateInstanceRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7480700f1dd5ca1, []int{3}
}

func (m *FactoryCreateInstanceRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactoryCreateInstanceRs.Unmarshal(m, b)
}
func (m *FactoryCreateInstanceRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactoryCreateInstanceRs.Marshal(b, m, deterministic)
}
func (m *FactoryCreateInstanceRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactoryCreateInstanceRs.Merge(m, src)
}
func (m *FactoryCreateInstanceRs) XXX_Size() int {
	return xxx_messageInfo_FactoryCreateInstanceRs.Size(m)
}
func (m *FactoryCreateInstanceRs) XXX_DiscardUnknown() {
	xxx_messageInfo_FactoryCreateInstanceRs.DiscardUnknown(m)
}

var xxx_messageInfo_FactoryCreateInstanceRs proto.InternalMessageInfo

func (m *FactoryCreateInstanceRs) GetInstanceKey() string {
	if m != nil {
		return m.InstanceKey
	}
	return ""
}

type FactoryListInstancesRq struct {
	Filter               string   `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	FilterType           string   `protobuf:"bytes,2,opt,name=FilterType,proto3" json:"FilterType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FactoryListInstancesRq) Reset()         { *m = FactoryListInstancesRq{} }
func (m *FactoryListInstancesRq) String() string { return proto.CompactTextString(m) }
func (*FactoryListInstancesRq) ProtoMessage()    {}
func (*FactoryListInstancesRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7480700f1dd5ca1, []int{4}
}

func (m *FactoryListInstancesRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactoryListInstancesRq.Unmarshal(m, b)
}
func (m *FactoryListInstancesRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactoryListInstancesRq.Marshal(b, m, deterministic)
}
func (m *FactoryListInstancesRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactoryListInstancesRq.Merge(m, src)
}
func (m *FactoryListInstancesRq) XXX_Size() int {
	return xxx_messageInfo_FactoryListInstancesRq.Size(m)
}
func (m *FactoryListInstancesRq) XXX_DiscardUnknown() {
	xxx_messageInfo_FactoryListInstancesRq.DiscardUnknown(m)
}

var xxx_messageInfo_FactoryListInstancesRq proto.InternalMessageInfo

func (m *FactoryListInstancesRq) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *FactoryListInstancesRq) GetFilterType() string {
	if m != nil {
		return m.FilterType
	}
	return ""
}

type FactoryListInstancesRs struct {
	Sequence             []*Instance `protobuf:"bytes,1,rep,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FactoryListInstancesRs) Reset()         { *m = FactoryListInstancesRs{} }
func (m *FactoryListInstancesRs) String() string { return proto.CompactTextString(m) }
func (*FactoryListInstancesRs) ProtoMessage()    {}
func (*FactoryListInstancesRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7480700f1dd5ca1, []int{5}
}

func (m *FactoryListInstancesRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactoryListInstancesRs.Unmarshal(m, b)
}
func (m *FactoryListInstancesRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactoryListInstancesRs.Marshal(b, m, deterministic)
}
func (m *FactoryListInstancesRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactoryListInstancesRs.Merge(m, src)
}
func (m *FactoryListInstancesRs) XXX_Size() int {
	return xxx_messageInfo_FactoryListInstancesRs.Size(m)
}
func (m *FactoryListInstancesRs) XXX_DiscardUnknown() {
	xxx_messageInfo_FactoryListInstancesRs.DiscardUnknown(m)
}

var xxx_messageInfo_FactoryListInstancesRs proto.InternalMessageInfo

func (m *FactoryListInstancesRs) GetSequence() []*Instance {
	if m != nil {
		return m.Sequence
	}
	return nil
}

type Instance struct {
	InstanceKey          string   `protobuf:"bytes,1,opt,name=InstanceKey,proto3" json:"InstanceKey,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Subject              string   `protobuf:"bytes,3,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Priority             int32    `protobuf:"varint,4,opt,name=Priority,proto3" json:"Priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7480700f1dd5ca1, []int{6}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetInstanceKey() string {
	if m != nil {
		return m.InstanceKey
	}
	return ""
}

func (m *Instance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Instance) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Instance) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type FactoryGetDefinitionRq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ProcessLanguage      string   `protobuf:"bytes,2,opt,name=ProcessLanguage,proto3" json:"ProcessLanguage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FactoryGetDefinitionRq) Reset()         { *m = FactoryGetDefinitionRq{} }
func (m *FactoryGetDefinitionRq) String() string { return proto.CompactTextString(m) }
func (*FactoryGetDefinitionRq) ProtoMessage()    {}
func (*FactoryGetDefinitionRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7480700f1dd5ca1, []int{7}
}

func (m *FactoryGetDefinitionRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactoryGetDefinitionRq.Unmarshal(m, b)
}
func (m *FactoryGetDefinitionRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactoryGetDefinitionRq.Marshal(b, m, deterministic)
}
func (m *FactoryGetDefinitionRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactoryGetDefinitionRq.Merge(m, src)
}
func (m *FactoryGetDefinitionRq) XXX_Size() int {
	return xxx_messageInfo_FactoryGetDefinitionRq.Size(m)
}
func (m *FactoryGetDefinitionRq) XXX_DiscardUnknown() {
	xxx_messageInfo_FactoryGetDefinitionRq.DiscardUnknown(m)
}

var xxx_messageInfo_FactoryGetDefinitionRq proto.InternalMessageInfo

func (m *FactoryGetDefinitionRq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FactoryGetDefinitionRq) GetProcessLanguage() string {
	if m != nil {
		return m.ProcessLanguage
	}
	return ""
}

type FactoryGetDefinitionRs struct {
	Definition           string   `protobuf:"bytes,1,opt,name=Definition,proto3" json:"Definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FactoryGetDefinitionRs) Reset()         { *m = FactoryGetDefinitionRs{} }
func (m *FactoryGetDefinitionRs) String() string { return proto.CompactTextString(m) }
func (*FactoryGetDefinitionRs) ProtoMessage()    {}
func (*FactoryGetDefinitionRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7480700f1dd5ca1, []int{8}
}

func (m *FactoryGetDefinitionRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactoryGetDefinitionRs.Unmarshal(m, b)
}
func (m *FactoryGetDefinitionRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactoryGetDefinitionRs.Marshal(b, m, deterministic)
}
func (m *FactoryGetDefinitionRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactoryGetDefinitionRs.Merge(m, src)
}
func (m *FactoryGetDefinitionRs) XXX_Size() int {
	return xxx_messageInfo_FactoryGetDefinitionRs.Size(m)
}
func (m *FactoryGetDefinitionRs) XXX_DiscardUnknown() {
	xxx_messageInfo_FactoryGetDefinitionRs.DiscardUnknown(m)
}

var xxx_messageInfo_FactoryGetDefinitionRs proto.InternalMessageInfo

func (m *FactoryGetDefinitionRs) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

type FactorySetDefinitionRq struct {
	Key                  string   `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	ProcessLanguage      string   `protobuf:"bytes,1,opt,name=ProcessLanguage,proto3" json:"ProcessLanguage,omitempty"`
	Definition           string   `protobuf:"bytes,2,opt,name=Definition,proto3" json:"Definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FactorySetDefinitionRq) Reset()         { *m = FactorySetDefinitionRq{} }
func (m *FactorySetDefinitionRq) String() string { return proto.CompactTextString(m) }
func (*FactorySetDefinitionRq) ProtoMessage()    {}
func (*FactorySetDefinitionRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7480700f1dd5ca1, []int{9}
}

func (m *FactorySetDefinitionRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactorySetDefinitionRq.Unmarshal(m, b)
}
func (m *FactorySetDefinitionRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactorySetDefinitionRq.Marshal(b, m, deterministic)
}
func (m *FactorySetDefinitionRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactorySetDefinitionRq.Merge(m, src)
}
func (m *FactorySetDefinitionRq) XXX_Size() int {
	return xxx_messageInfo_FactorySetDefinitionRq.Size(m)
}
func (m *FactorySetDefinitionRq) XXX_DiscardUnknown() {
	xxx_messageInfo_FactorySetDefinitionRq.DiscardUnknown(m)
}

var xxx_messageInfo_FactorySetDefinitionRq proto.InternalMessageInfo

func (m *FactorySetDefinitionRq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FactorySetDefinitionRq) GetProcessLanguage() string {
	if m != nil {
		return m.ProcessLanguage
	}
	return ""
}

func (m *FactorySetDefinitionRq) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

type FactorySetDefinitionRs struct {
	Definition           string   `protobuf:"bytes,1,opt,name=Definition,proto3" json:"Definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FactorySetDefinitionRs) Reset()         { *m = FactorySetDefinitionRs{} }
func (m *FactorySetDefinitionRs) String() string { return proto.CompactTextString(m) }
func (*FactorySetDefinitionRs) ProtoMessage()    {}
func (*FactorySetDefinitionRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7480700f1dd5ca1, []int{10}
}

func (m *FactorySetDefinitionRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactorySetDefinitionRs.Unmarshal(m, b)
}
func (m *FactorySetDefinitionRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactorySetDefinitionRs.Marshal(b, m, deterministic)
}
func (m *FactorySetDefinitionRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactorySetDefinitionRs.Merge(m, src)
}
func (m *FactorySetDefinitionRs) XXX_Size() int {
	return xxx_messageInfo_FactorySetDefinitionRs.Size(m)
}
func (m *FactorySetDefinitionRs) XXX_DiscardUnknown() {
	xxx_messageInfo_FactorySetDefinitionRs.DiscardUnknown(m)
}

var xxx_messageInfo_FactorySetDefinitionRs proto.InternalMessageInfo

func (m *FactorySetDefinitionRs) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

func init() {
	proto.RegisterType((*FactoryGetPropertiesRq)(nil), "grpc.FactoryGetPropertiesRq")
	proto.RegisterType((*FactoryGetPropertiesRs)(nil), "grpc.FactoryGetPropertiesRs")
	proto.RegisterType((*FactoryCreateInstanceRq)(nil), "grpc.FactoryCreateInstanceRq")
	proto.RegisterType((*FactoryCreateInstanceRs)(nil), "grpc.FactoryCreateInstanceRs")
	proto.RegisterType((*FactoryListInstancesRq)(nil), "grpc.FactoryListInstancesRq")
	proto.RegisterType((*FactoryListInstancesRs)(nil), "grpc.FactoryListInstancesRs")
	proto.RegisterType((*Instance)(nil), "grpc.Instance")
	proto.RegisterType((*FactoryGetDefinitionRq)(nil), "grpc.FactoryGetDefinitionRq")
	proto.RegisterType((*FactoryGetDefinitionRs)(nil), "grpc.FactoryGetDefinitionRs")
	proto.RegisterType((*FactorySetDefinitionRq)(nil), "grpc.FactorySetDefinitionRq")
	proto.RegisterType((*FactorySetDefinitionRs)(nil), "grpc.FactorySetDefinitionRs")
}

func init() { proto.RegisterFile("factory.proto", fileDescriptor_f7480700f1dd5ca1) }

var fileDescriptor_f7480700f1dd5ca1 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0xdb, 0x30,
	0x0c, 0x86, 0xeb, 0x34, 0xc9, 0x18, 0xb4, 0xeb, 0x74, 0xe8, 0x8c, 0x60, 0x1b, 0x0c, 0x9d, 0x82,
	0x60, 0xc8, 0xa1, 0xbb, 0x14, 0xd8, 0xb1, 0x59, 0x87, 0xa2, 0x45, 0x17, 0xd8, 0x7d, 0x01, 0xc5,
	0x63, 0x33, 0x0d, 0x89, 0xed, 0x48, 0x4a, 0xd1, 0xbc, 0xea, 0x9e, 0x63, 0x97, 0xdd, 0x06, 0x29,
	0xb6, 0xa3, 0xf8, 0xaf, 0xdb, 0xcd, 0xfc, 0x48, 0x91, 0x1f, 0x3f, 0x52, 0x32, 0x9c, 0x3c, 0xb2,
	0x48, 0x25, 0x62, 0x3b, 0x49, 0x45, 0xa2, 0x12, 0xd2, 0x59, 0x88, 0x34, 0xa2, 0x63, 0x38, 0xbf,
	0xde, 0xc1, 0x5f, 0x51, 0xcd, 0x44, 0x92, 0xa2, 0x50, 0x1c, 0x65, 0xb0, 0x26, 0x67, 0xe0, 0xde,
	0xe2, 0xd6, 0x73, 0x7c, 0x67, 0xf4, 0x2a, 0xd0, 0x9f, 0xf4, 0xb7, 0xd3, 0x10, 0x2c, 0xab, 0xc1,
	0x84, 0x40, 0xe7, 0x9e, 0xad, 0xd0, 0x3b, 0x32, 0x90, 0xf9, 0x26, 0x1e, 0xf4, 0xc2, 0xcd, 0xfc,
	0x27, 0x46, 0xca, 0x73, 0x0d, 0x9c, 0x9b, 0xc4, 0x87, 0xc1, 0x14, 0x65, 0x24, 0x78, 0xaa, 0x78,
	0x12, 0x7b, 0x1d, 0xe3, 0xb5, 0x21, 0xf2, 0x11, 0xde, 0x5c, 0x25, 0xb1, 0xc2, 0x67, 0x35, 0x65,
	0x8a, 0x85, 0xd1, 0x0f, 0x5c, 0x31, 0xef, 0xd8, 0xc4, 0x55, 0x1d, 0x64, 0x0c, 0x67, 0x01, 0xca,
	0xcd, 0xd2, 0x0e, 0xee, 0x9a, 0xe0, 0x0a, 0x4e, 0x3e, 0x00, 0x7c, 0x79, 0x4e, 0xb9, 0x60, 0xa6,
	0x74, 0xcf, 0x77, 0x46, 0x6e, 0x60, 0x21, 0xf4, 0x8f, 0x03, 0x6f, 0xb3, 0xb6, 0xaf, 0x04, 0x32,
	0x85, 0x37, 0xb1, 0x54, 0x2c, 0x8e, 0x30, 0x58, 0xeb, 0x3a, 0xa1, 0x62, 0x42, 0xdd, 0xac, 0x56,
	0xf8, 0x9d, 0x33, 0x85, 0xcb, 0x9d, 0x08, 0xfd, 0xa0, 0x82, 0xeb, 0x1e, 0xbf, 0xcd, 0x25, 0x8a,
	0x27, 0x14, 0x5a, 0xab, 0x9d, 0x30, 0x36, 0x54, 0x68, 0xe6, 0xd6, 0x6b, 0xd6, 0x69, 0xd5, 0xec,
	0xb8, 0xaa, 0x99, 0x0f, 0x03, 0x4b, 0x9a, 0x4c, 0x00, 0x1b, 0xd2, 0xbd, 0x67, 0xad, 0x69, 0x4a,
	0x7d, 0x13, 0x60, 0x21, 0xf4, 0x73, 0x53, 0xeb, 0x52, 0x27, 0xcf, 0xad, 0xfd, 0xe8, 0x6d, 0x88,
	0xce, 0x8a, 0x75, 0xb9, 0xe3, 0x52, 0xe5, 0x1e, 0xbd, 0x5b, 0xe7, 0xd0, 0xbd, 0xe6, 0x4b, 0x85,
	0x22, 0x3b, 0x96, 0x59, 0x86, 0x8e, 0xf9, 0x7a, 0xd8, 0xa6, 0xf9, 0xea, 0x58, 0x08, 0x9d, 0x36,
	0x64, 0x94, 0x64, 0x0c, 0x7d, 0x89, 0xeb, 0x0d, 0xc6, 0x11, 0x7a, 0x8e, 0xef, 0x8e, 0x06, 0x17,
	0xa7, 0x13, 0xbd, 0xe0, 0x93, 0x82, 0x71, 0xe1, 0xa7, 0x4f, 0xd0, 0xcf, 0xd1, 0x97, 0xbb, 0xf8,
	0xcf, 0x45, 0x1e, 0x42, 0x7f, 0x26, 0x78, 0x22, 0xb8, 0xda, 0x9a, 0x79, 0x1d, 0x07, 0x85, 0x4d,
	0x1f, 0xec, 0xeb, 0x33, 0xc5, 0x47, 0x1e, 0x73, 0x3d, 0xa6, 0xba, 0xbb, 0x46, 0x46, 0xf0, 0x7a,
	0x26, 0x92, 0x08, 0xa5, 0xbc, 0x63, 0xf1, 0x62, 0xc3, 0x16, 0x39, 0x81, 0x32, 0x4c, 0x2f, 0x1b,
	0xb2, 0x4a, 0xad, 0xe6, 0xde, 0xce, 0x92, 0x5b, 0x08, 0x55, 0xc5, 0xc9, 0xb0, 0x9e, 0x8f, 0xdb,
	0xca, 0xc7, 0xa9, 0xe5, 0x53, 0xaa, 0x7a, 0x54, 0xa9, 0x7a, 0xd9, 0x50, 0xf5, 0x45, 0xbe, 0x17,
	0xbf, 0x5c, 0xe8, 0x65, 0x47, 0xc9, 0x2d, 0x9c, 0x1c, 0xbc, 0x41, 0xe4, 0xdd, 0x6e, 0xdc, 0xf5,
	0x8f, 0xd9, 0xb0, 0xcd, 0x2b, 0x75, 0xb2, 0xf0, 0x9f, 0x93, 0xc9, 0xd6, 0x64, 0x6b, 0x72, 0x0f,
	0xa7, 0x87, 0x77, 0x85, 0xbc, 0x3f, 0x88, 0x2f, 0xbf, 0x21, 0xc3, 0x56, 0xb7, 0x21, 0x77, 0xb0,
	0xec, 0x25, 0x72, 0xa5, 0xab, 0x35, 0x6c, 0xf3, 0xca, 0x4c, 0xb6, 0xbd, 0xa6, 0xd5, 0x4e, 0xed,
	0x3d, 0x18, 0xb6, 0x79, 0x73, 0xd9, 0x1a, 0x93, 0x85, 0xad, 0xc9, 0x4a, 0xc3, 0x9f, 0x77, 0xcd,
	0x5f, 0xe9, 0xd3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x20, 0xa8, 0xe4, 0xa6, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FactoryClient is the client API for Factory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FactoryClient interface {
	GetProperties(ctx context.Context, in *FactoryGetPropertiesRq, opts ...grpc.CallOption) (*FactoryGetPropertiesRs, error)
	SetProperties(ctx context.Context, in *FactoryGetPropertiesRs, opts ...grpc.CallOption) (*FactoryGetPropertiesRq, error)
	CreateInstance(ctx context.Context, in *FactoryCreateInstanceRq, opts ...grpc.CallOption) (*FactoryCreateInstanceRs, error)
	ListInstances(ctx context.Context, in *FactoryListInstancesRq, opts ...grpc.CallOption) (*FactoryListInstancesRs, error)
	GetDefinition(ctx context.Context, in *FactoryGetDefinitionRq, opts ...grpc.CallOption) (*FactoryGetDefinitionRs, error)
	SetDefinition(ctx context.Context, in *FactorySetDefinitionRq, opts ...grpc.CallOption) (*FactorySetDefinitionRs, error)
}

type factoryClient struct {
	cc *grpc.ClientConn
}

func NewFactoryClient(cc *grpc.ClientConn) FactoryClient {
	return &factoryClient{cc}
}

func (c *factoryClient) GetProperties(ctx context.Context, in *FactoryGetPropertiesRq, opts ...grpc.CallOption) (*FactoryGetPropertiesRs, error) {
	out := new(FactoryGetPropertiesRs)
	err := c.cc.Invoke(ctx, "/grpc.Factory/GetProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *factoryClient) SetProperties(ctx context.Context, in *FactoryGetPropertiesRs, opts ...grpc.CallOption) (*FactoryGetPropertiesRq, error) {
	out := new(FactoryGetPropertiesRq)
	err := c.cc.Invoke(ctx, "/grpc.Factory/SetProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *factoryClient) CreateInstance(ctx context.Context, in *FactoryCreateInstanceRq, opts ...grpc.CallOption) (*FactoryCreateInstanceRs, error) {
	out := new(FactoryCreateInstanceRs)
	err := c.cc.Invoke(ctx, "/grpc.Factory/CreateInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *factoryClient) ListInstances(ctx context.Context, in *FactoryListInstancesRq, opts ...grpc.CallOption) (*FactoryListInstancesRs, error) {
	out := new(FactoryListInstancesRs)
	err := c.cc.Invoke(ctx, "/grpc.Factory/ListInstances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *factoryClient) GetDefinition(ctx context.Context, in *FactoryGetDefinitionRq, opts ...grpc.CallOption) (*FactoryGetDefinitionRs, error) {
	out := new(FactoryGetDefinitionRs)
	err := c.cc.Invoke(ctx, "/grpc.Factory/GetDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *factoryClient) SetDefinition(ctx context.Context, in *FactorySetDefinitionRq, opts ...grpc.CallOption) (*FactorySetDefinitionRs, error) {
	out := new(FactorySetDefinitionRs)
	err := c.cc.Invoke(ctx, "/grpc.Factory/SetDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FactoryServer is the server API for Factory service.
type FactoryServer interface {
	GetProperties(context.Context, *FactoryGetPropertiesRq) (*FactoryGetPropertiesRs, error)
	SetProperties(context.Context, *FactoryGetPropertiesRs) (*FactoryGetPropertiesRq, error)
	CreateInstance(context.Context, *FactoryCreateInstanceRq) (*FactoryCreateInstanceRs, error)
	ListInstances(context.Context, *FactoryListInstancesRq) (*FactoryListInstancesRs, error)
	GetDefinition(context.Context, *FactoryGetDefinitionRq) (*FactoryGetDefinitionRs, error)
	SetDefinition(context.Context, *FactorySetDefinitionRq) (*FactorySetDefinitionRs, error)
}

// UnimplementedFactoryServer can be embedded to have forward compatible implementations.
type UnimplementedFactoryServer struct {
}

func (*UnimplementedFactoryServer) GetProperties(ctx context.Context, req *FactoryGetPropertiesRq) (*FactoryGetPropertiesRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProperties not implemented")
}
func (*UnimplementedFactoryServer) SetProperties(ctx context.Context, req *FactoryGetPropertiesRs) (*FactoryGetPropertiesRq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProperties not implemented")
}
func (*UnimplementedFactoryServer) CreateInstance(ctx context.Context, req *FactoryCreateInstanceRq) (*FactoryCreateInstanceRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstance not implemented")
}
func (*UnimplementedFactoryServer) ListInstances(ctx context.Context, req *FactoryListInstancesRq) (*FactoryListInstancesRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstances not implemented")
}
func (*UnimplementedFactoryServer) GetDefinition(ctx context.Context, req *FactoryGetDefinitionRq) (*FactoryGetDefinitionRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefinition not implemented")
}
func (*UnimplementedFactoryServer) SetDefinition(ctx context.Context, req *FactorySetDefinitionRq) (*FactorySetDefinitionRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefinition not implemented")
}

func RegisterFactoryServer(s *grpc.Server, srv FactoryServer) {
	s.RegisterService(&_Factory_serviceDesc, srv)
}

func _Factory_GetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryGetPropertiesRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactoryServer).GetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Factory/GetProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactoryServer).GetProperties(ctx, req.(*FactoryGetPropertiesRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Factory_SetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryGetPropertiesRs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactoryServer).SetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Factory/SetProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactoryServer).SetProperties(ctx, req.(*FactoryGetPropertiesRs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Factory_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryCreateInstanceRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactoryServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Factory/CreateInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactoryServer).CreateInstance(ctx, req.(*FactoryCreateInstanceRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Factory_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryListInstancesRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactoryServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Factory/ListInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactoryServer).ListInstances(ctx, req.(*FactoryListInstancesRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Factory_GetDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryGetDefinitionRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactoryServer).GetDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Factory/GetDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactoryServer).GetDefinition(ctx, req.(*FactoryGetDefinitionRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Factory_SetDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactorySetDefinitionRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactoryServer).SetDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Factory/SetDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactoryServer).SetDefinition(ctx, req.(*FactorySetDefinitionRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Factory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Factory",
	HandlerType: (*FactoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProperties",
			Handler:    _Factory_GetProperties_Handler,
		},
		{
			MethodName: "SetProperties",
			Handler:    _Factory_SetProperties_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _Factory_CreateInstance_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _Factory_ListInstances_Handler,
		},
		{
			MethodName: "GetDefinition",
			Handler:    _Factory_GetDefinition_Handler,
		},
		{
			MethodName: "SetDefinition",
			Handler:    _Factory_SetDefinition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "factory.proto",
}
