// Code generated by protoc-gen-go. DO NOT EDIT.
// source: instance.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State int32

const (
	State_OPEN_NOTRUNNING                     State = 0
	State_OPEN_NOTRUNNING_SUSPENDED           State = 1
	State_OPEN_RUNNING                        State = 2
	State_CLOSED_COMPLETED                    State = 3
	State_CLOSED_ABNORMALCOMPLETED            State = 4
	State_CLOSED_ABNORMALCOMPLETED_TERMINATED State = 5
	State_CLOSED_ABNORMALCOMPLETED_ABORTED    State = 6
)

var State_name = map[int32]string{
	0: "OPEN_NOTRUNNING",
	1: "OPEN_NOTRUNNING_SUSPENDED",
	2: "OPEN_RUNNING",
	3: "CLOSED_COMPLETED",
	4: "CLOSED_ABNORMALCOMPLETED",
	5: "CLOSED_ABNORMALCOMPLETED_TERMINATED",
	6: "CLOSED_ABNORMALCOMPLETED_ABORTED",
}

var State_value = map[string]int32{
	"OPEN_NOTRUNNING":                     0,
	"OPEN_NOTRUNNING_SUSPENDED":           1,
	"OPEN_RUNNING":                        2,
	"CLOSED_COMPLETED":                    3,
	"CLOSED_ABNORMALCOMPLETED":            4,
	"CLOSED_ABNORMALCOMPLETED_TERMINATED": 5,
	"CLOSED_ABNORMALCOMPLETED_ABORTED":    6,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{0}
}

type InstanceGetPropertiesRq struct {
	InstanceKey          string   `protobuf:"bytes,1,opt,name=InstanceKey,proto3" json:"InstanceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceGetPropertiesRq) Reset()         { *m = InstanceGetPropertiesRq{} }
func (m *InstanceGetPropertiesRq) String() string { return proto.CompactTextString(m) }
func (*InstanceGetPropertiesRq) ProtoMessage()    {}
func (*InstanceGetPropertiesRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{0}
}

func (m *InstanceGetPropertiesRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceGetPropertiesRq.Unmarshal(m, b)
}
func (m *InstanceGetPropertiesRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceGetPropertiesRq.Marshal(b, m, deterministic)
}
func (m *InstanceGetPropertiesRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceGetPropertiesRq.Merge(m, src)
}
func (m *InstanceGetPropertiesRq) XXX_Size() int {
	return xxx_messageInfo_InstanceGetPropertiesRq.Size(m)
}
func (m *InstanceGetPropertiesRq) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceGetPropertiesRq.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceGetPropertiesRq proto.InternalMessageInfo

func (m *InstanceGetPropertiesRq) GetInstanceKey() string {
	if m != nil {
		return m.InstanceKey
	}
	return ""
}

type InstanceGetPropertiesRs struct {
	InstanceKey          string   `protobuf:"bytes,1,opt,name=InstanceKey,proto3" json:"InstanceKey,omitempty"`
	State                State    `protobuf:"varint,2,opt,name=State,proto3,enum=grpc.State" json:"State,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Subject              string   `protobuf:"bytes,4,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	FactoryKey           string   `protobuf:"bytes,6,opt,name=FactoryKey,proto3" json:"FactoryKey,omitempty"`
	Observers            []string `protobuf:"bytes,7,rep,name=Observers,proto3" json:"Observers,omitempty"`
	ContextData          string   `protobuf:"bytes,8,opt,name=ContextData,proto3" json:"ContextData,omitempty"`
	ResultData           string   `protobuf:"bytes,9,opt,name=ResultData,proto3" json:"ResultData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceGetPropertiesRs) Reset()         { *m = InstanceGetPropertiesRs{} }
func (m *InstanceGetPropertiesRs) String() string { return proto.CompactTextString(m) }
func (*InstanceGetPropertiesRs) ProtoMessage()    {}
func (*InstanceGetPropertiesRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{1}
}

func (m *InstanceGetPropertiesRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceGetPropertiesRs.Unmarshal(m, b)
}
func (m *InstanceGetPropertiesRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceGetPropertiesRs.Marshal(b, m, deterministic)
}
func (m *InstanceGetPropertiesRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceGetPropertiesRs.Merge(m, src)
}
func (m *InstanceGetPropertiesRs) XXX_Size() int {
	return xxx_messageInfo_InstanceGetPropertiesRs.Size(m)
}
func (m *InstanceGetPropertiesRs) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceGetPropertiesRs.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceGetPropertiesRs proto.InternalMessageInfo

func (m *InstanceGetPropertiesRs) GetInstanceKey() string {
	if m != nil {
		return m.InstanceKey
	}
	return ""
}

func (m *InstanceGetPropertiesRs) GetState() State {
	if m != nil {
		return m.State
	}
	return State_OPEN_NOTRUNNING
}

func (m *InstanceGetPropertiesRs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstanceGetPropertiesRs) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *InstanceGetPropertiesRs) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InstanceGetPropertiesRs) GetFactoryKey() string {
	if m != nil {
		return m.FactoryKey
	}
	return ""
}

func (m *InstanceGetPropertiesRs) GetObservers() []string {
	if m != nil {
		return m.Observers
	}
	return nil
}

func (m *InstanceGetPropertiesRs) GetContextData() string {
	if m != nil {
		return m.ContextData
	}
	return ""
}

func (m *InstanceGetPropertiesRs) GetResultData() string {
	if m != nil {
		return m.ResultData
	}
	return ""
}

type InstanceSetPropertiesRq struct {
	InstanceKey          string   `protobuf:"bytes,1,opt,name=InstanceKey,proto3" json:"InstanceKey,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Priority             string   `protobuf:"bytes,4,opt,name=Priority,proto3" json:"Priority,omitempty"`
	ContextData          string   `protobuf:"bytes,5,opt,name=ContextData,proto3" json:"ContextData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceSetPropertiesRq) Reset()         { *m = InstanceSetPropertiesRq{} }
func (m *InstanceSetPropertiesRq) String() string { return proto.CompactTextString(m) }
func (*InstanceSetPropertiesRq) ProtoMessage()    {}
func (*InstanceSetPropertiesRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{2}
}

func (m *InstanceSetPropertiesRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceSetPropertiesRq.Unmarshal(m, b)
}
func (m *InstanceSetPropertiesRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceSetPropertiesRq.Marshal(b, m, deterministic)
}
func (m *InstanceSetPropertiesRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceSetPropertiesRq.Merge(m, src)
}
func (m *InstanceSetPropertiesRq) XXX_Size() int {
	return xxx_messageInfo_InstanceSetPropertiesRq.Size(m)
}
func (m *InstanceSetPropertiesRq) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceSetPropertiesRq.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceSetPropertiesRq proto.InternalMessageInfo

func (m *InstanceSetPropertiesRq) GetInstanceKey() string {
	if m != nil {
		return m.InstanceKey
	}
	return ""
}

func (m *InstanceSetPropertiesRq) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *InstanceSetPropertiesRq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InstanceSetPropertiesRq) GetPriority() string {
	if m != nil {
		return m.Priority
	}
	return ""
}

func (m *InstanceSetPropertiesRq) GetContextData() string {
	if m != nil {
		return m.ContextData
	}
	return ""
}

type InstanceSubscribeRq struct {
	InstanceKey          string   `protobuf:"bytes,1,opt,name=InstanceKey,proto3" json:"InstanceKey,omitempty"`
	ObserverKey          string   `protobuf:"bytes,2,opt,name=ObserverKey,proto3" json:"ObserverKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceSubscribeRq) Reset()         { *m = InstanceSubscribeRq{} }
func (m *InstanceSubscribeRq) String() string { return proto.CompactTextString(m) }
func (*InstanceSubscribeRq) ProtoMessage()    {}
func (*InstanceSubscribeRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{3}
}

func (m *InstanceSubscribeRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceSubscribeRq.Unmarshal(m, b)
}
func (m *InstanceSubscribeRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceSubscribeRq.Marshal(b, m, deterministic)
}
func (m *InstanceSubscribeRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceSubscribeRq.Merge(m, src)
}
func (m *InstanceSubscribeRq) XXX_Size() int {
	return xxx_messageInfo_InstanceSubscribeRq.Size(m)
}
func (m *InstanceSubscribeRq) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceSubscribeRq.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceSubscribeRq proto.InternalMessageInfo

func (m *InstanceSubscribeRq) GetInstanceKey() string {
	if m != nil {
		return m.InstanceKey
	}
	return ""
}

func (m *InstanceSubscribeRq) GetObserverKey() string {
	if m != nil {
		return m.ObserverKey
	}
	return ""
}

type InstanceSubscribeRs struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceSubscribeRs) Reset()         { *m = InstanceSubscribeRs{} }
func (m *InstanceSubscribeRs) String() string { return proto.CompactTextString(m) }
func (*InstanceSubscribeRs) ProtoMessage()    {}
func (*InstanceSubscribeRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{4}
}

func (m *InstanceSubscribeRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceSubscribeRs.Unmarshal(m, b)
}
func (m *InstanceSubscribeRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceSubscribeRs.Marshal(b, m, deterministic)
}
func (m *InstanceSubscribeRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceSubscribeRs.Merge(m, src)
}
func (m *InstanceSubscribeRs) XXX_Size() int {
	return xxx_messageInfo_InstanceSubscribeRs.Size(m)
}
func (m *InstanceSubscribeRs) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceSubscribeRs.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceSubscribeRs proto.InternalMessageInfo

type InstanceListActivitiesRq struct {
	InstanceKey          string   `protobuf:"bytes,1,opt,name=InstanceKey,proto3" json:"InstanceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceListActivitiesRq) Reset()         { *m = InstanceListActivitiesRq{} }
func (m *InstanceListActivitiesRq) String() string { return proto.CompactTextString(m) }
func (*InstanceListActivitiesRq) ProtoMessage()    {}
func (*InstanceListActivitiesRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{5}
}

func (m *InstanceListActivitiesRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceListActivitiesRq.Unmarshal(m, b)
}
func (m *InstanceListActivitiesRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceListActivitiesRq.Marshal(b, m, deterministic)
}
func (m *InstanceListActivitiesRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceListActivitiesRq.Merge(m, src)
}
func (m *InstanceListActivitiesRq) XXX_Size() int {
	return xxx_messageInfo_InstanceListActivitiesRq.Size(m)
}
func (m *InstanceListActivitiesRq) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceListActivitiesRq.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceListActivitiesRq proto.InternalMessageInfo

func (m *InstanceListActivitiesRq) GetInstanceKey() string {
	if m != nil {
		return m.InstanceKey
	}
	return ""
}

type InstanceListActivitiesRs struct {
	ActivityKey          string   `protobuf:"bytes,1,opt,name=ActivityKey,proto3" json:"ActivityKey,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Assignee             string   `protobuf:"bytes,4,opt,name=Assignee,proto3" json:"Assignee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceListActivitiesRs) Reset()         { *m = InstanceListActivitiesRs{} }
func (m *InstanceListActivitiesRs) String() string { return proto.CompactTextString(m) }
func (*InstanceListActivitiesRs) ProtoMessage()    {}
func (*InstanceListActivitiesRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{6}
}

func (m *InstanceListActivitiesRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceListActivitiesRs.Unmarshal(m, b)
}
func (m *InstanceListActivitiesRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceListActivitiesRs.Marshal(b, m, deterministic)
}
func (m *InstanceListActivitiesRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceListActivitiesRs.Merge(m, src)
}
func (m *InstanceListActivitiesRs) XXX_Size() int {
	return xxx_messageInfo_InstanceListActivitiesRs.Size(m)
}
func (m *InstanceListActivitiesRs) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceListActivitiesRs.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceListActivitiesRs proto.InternalMessageInfo

func (m *InstanceListActivitiesRs) GetActivityKey() string {
	if m != nil {
		return m.ActivityKey
	}
	return ""
}

func (m *InstanceListActivitiesRs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstanceListActivitiesRs) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InstanceListActivitiesRs) GetAssignee() string {
	if m != nil {
		return m.Assignee
	}
	return ""
}

type InstanceChangeStateRq struct {
	InstanceKey          string   `protobuf:"bytes,1,opt,name=InstanceKey,proto3" json:"InstanceKey,omitempty"`
	State                State    `protobuf:"varint,2,opt,name=state,proto3,enum=grpc.State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceChangeStateRq) Reset()         { *m = InstanceChangeStateRq{} }
func (m *InstanceChangeStateRq) String() string { return proto.CompactTextString(m) }
func (*InstanceChangeStateRq) ProtoMessage()    {}
func (*InstanceChangeStateRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22322185b2070b, []int{7}
}

func (m *InstanceChangeStateRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceChangeStateRq.Unmarshal(m, b)
}
func (m *InstanceChangeStateRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceChangeStateRq.Marshal(b, m, deterministic)
}
func (m *InstanceChangeStateRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceChangeStateRq.Merge(m, src)
}
func (m *InstanceChangeStateRq) XXX_Size() int {
	return xxx_messageInfo_InstanceChangeStateRq.Size(m)
}
func (m *InstanceChangeStateRq) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceChangeStateRq.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceChangeStateRq proto.InternalMessageInfo

func (m *InstanceChangeStateRq) GetInstanceKey() string {
	if m != nil {
		return m.InstanceKey
	}
	return ""
}

func (m *InstanceChangeStateRq) GetState() State {
	if m != nil {
		return m.State
	}
	return State_OPEN_NOTRUNNING
}

func init() {
	proto.RegisterEnum("grpc.State", State_name, State_value)
	proto.RegisterType((*InstanceGetPropertiesRq)(nil), "grpc.InstanceGetPropertiesRq")
	proto.RegisterType((*InstanceGetPropertiesRs)(nil), "grpc.InstanceGetPropertiesRs")
	proto.RegisterType((*InstanceSetPropertiesRq)(nil), "grpc.InstanceSetPropertiesRq")
	proto.RegisterType((*InstanceSubscribeRq)(nil), "grpc.InstanceSubscribeRq")
	proto.RegisterType((*InstanceSubscribeRs)(nil), "grpc.InstanceSubscribeRs")
	proto.RegisterType((*InstanceListActivitiesRq)(nil), "grpc.InstanceListActivitiesRq")
	proto.RegisterType((*InstanceListActivitiesRs)(nil), "grpc.InstanceListActivitiesRs")
	proto.RegisterType((*InstanceChangeStateRq)(nil), "grpc.InstanceChangeStateRq")
}

func init() { proto.RegisterFile("instance.proto", fileDescriptor_fd22322185b2070b) }

var fileDescriptor_fd22322185b2070b = []byte{
	// 578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x8e, 0xd2, 0x50,
	0x10, 0xb6, 0xfc, 0x2d, 0x0c, 0x8a, 0x64, 0xd6, 0x8d, 0x5d, 0xdc, 0xdd, 0xd4, 0x6a, 0x22, 0xf1,
	0x82, 0x8b, 0xf5, 0x52, 0x6f, 0xba, 0xb4, 0x12, 0x22, 0xb4, 0x4d, 0x0b, 0x17, 0x26, 0x26, 0xa4,
	0x34, 0x27, 0x58, 0xa3, 0x2d, 0xdb, 0x73, 0xd8, 0xc8, 0x4b, 0xf8, 0x28, 0xde, 0xf9, 0x14, 0xde,
	0xf8, 0x48, 0xe6, 0xb4, 0x14, 0x0e, 0xac, 0x45, 0x36, 0x7b, 0xc7, 0x7c, 0xdf, 0xcc, 0xd7, 0x99,
	0xe1, 0x9b, 0x16, 0x1a, 0x41, 0x48, 0x99, 0x17, 0xfa, 0xa4, 0x33, 0x8f, 0x23, 0x16, 0x61, 0x69,
	0x16, 0xcf, 0x7d, 0xf5, 0x2d, 0x3c, 0xed, 0xaf, 0xf0, 0x1e, 0x61, 0x76, 0x1c, 0xcd, 0x49, 0xcc,
	0x02, 0x42, 0x9d, 0x6b, 0x54, 0xa0, 0x9e, 0x51, 0x1f, 0xc8, 0x52, 0x96, 0x14, 0xa9, 0x5d, 0x73,
	0x44, 0x48, 0xfd, 0x59, 0xc8, 0xab, 0xa6, 0xff, 0xaf, 0xc6, 0xe7, 0x50, 0x76, 0x99, 0xc7, 0x88,
	0x5c, 0x50, 0xa4, 0x76, 0xe3, 0xb2, 0xde, 0xe1, 0x0d, 0x75, 0x12, 0xc8, 0x49, 0x19, 0x44, 0x28,
	0x99, 0xde, 0x37, 0x22, 0x17, 0x93, 0xea, 0xe4, 0x37, 0xca, 0x70, 0xe4, 0x2e, 0xa6, 0x5f, 0x88,
	0xcf, 0xe4, 0x52, 0x02, 0x67, 0x21, 0x7f, 0xa4, 0x4e, 0xa8, 0x1f, 0x07, 0x73, 0x16, 0x44, 0xa1,
	0x5c, 0x4e, 0x1f, 0x29, 0x40, 0x78, 0x01, 0xf0, 0xde, 0xf3, 0x59, 0x14, 0x2f, 0x79, 0x4f, 0x95,
	0x24, 0x41, 0x40, 0xf0, 0x0c, 0x6a, 0xd6, 0x94, 0x92, 0xf8, 0x86, 0xc4, 0x54, 0x3e, 0x52, 0x8a,
	0xed, 0x9a, 0xb3, 0x01, 0xb8, 0x7e, 0x37, 0x0a, 0x19, 0xf9, 0xce, 0x74, 0x8f, 0x79, 0x72, 0x35,
	0xd5, 0x17, 0x20, 0xae, 0xef, 0x10, 0xba, 0xf8, 0x9a, 0x26, 0xd4, 0x52, 0xfd, 0x0d, 0xa2, 0xfe,
	0x92, 0x36, 0x0b, 0x73, 0xef, 0xba, 0x6e, 0x71, 0xf2, 0xc2, 0xde, 0xc9, 0x8b, 0xb7, 0x27, 0x6f,
	0x41, 0xd5, 0x8e, 0x83, 0x28, 0x0e, 0xd8, 0x72, 0xb5, 0xb6, 0x75, 0xbc, 0x3b, 0x57, 0xf9, 0xd6,
	0x5c, 0xea, 0x47, 0x38, 0x5e, 0xb7, 0xbd, 0x98, 0x72, 0xd5, 0x29, 0x39, 0xa8, 0x65, 0x05, 0xea,
	0xd9, 0xfe, 0x78, 0x46, 0xda, 0xb6, 0x08, 0xa9, 0x27, 0xff, 0x92, 0xa6, 0xea, 0x3b, 0x90, 0x33,
	0x78, 0x10, 0x50, 0xa6, 0xf9, 0x2c, 0xb8, 0x09, 0x0e, 0x36, 0xe6, 0x0f, 0x29, 0xb7, 0x3c, 0xf9,
	0x1b, 0x57, 0xf1, 0x52, 0x28, 0x17, 0xa0, 0xb5, 0xed, 0x0a, 0x82, 0xed, 0x0e, 0x5a, 0xb1, 0x46,
	0x69, 0x30, 0x0b, 0x09, 0xc9, 0x56, 0x9c, 0xc5, 0xea, 0x27, 0x38, 0xc9, 0xfa, 0xe9, 0x7e, 0xf6,
	0xc2, 0x19, 0x49, 0x6d, 0x7e, 0x7d, 0xd8, 0x99, 0xd0, 0xdc, 0x33, 0x49, 0x98, 0xd7, 0x7f, 0xa4,
	0xd5, 0x29, 0xe1, 0x31, 0x3c, 0xb6, 0x6c, 0xc3, 0x9c, 0x98, 0xd6, 0xc8, 0x19, 0x9b, 0x66, 0xdf,
	0xec, 0x35, 0x1f, 0xe0, 0x39, 0x9c, 0xee, 0x80, 0x13, 0x77, 0xec, 0xda, 0x86, 0xa9, 0x1b, 0x7a,
	0x53, 0xc2, 0x26, 0x3c, 0x4c, 0xe8, 0xac, 0xa0, 0x80, 0x4f, 0xa0, 0xd9, 0x1d, 0x58, 0xae, 0xa1,
	0x4f, 0xba, 0xd6, 0xd0, 0x1e, 0x18, 0x23, 0x43, 0x6f, 0x16, 0xf1, 0x0c, 0xe4, 0x15, 0xaa, 0x5d,
	0x99, 0x96, 0x33, 0xd4, 0x06, 0x1b, 0xb6, 0x84, 0xaf, 0xe0, 0x45, 0x1e, 0x3b, 0x19, 0x19, 0xce,
	0xb0, 0x6f, 0x6a, 0x3c, 0xb1, 0x8c, 0x2f, 0x41, 0xc9, 0x4d, 0xd4, 0xae, 0x2c, 0x87, 0x67, 0x55,
	0x2e, 0x7f, 0x17, 0xa1, 0x9a, 0x6d, 0x01, 0x87, 0xf0, 0x68, 0xeb, 0xf5, 0x82, 0xe7, 0xe9, 0x12,
	0x72, 0xde, 0x5c, 0xad, 0xbd, 0x34, 0xe5, 0x72, 0xee, 0x3e, 0x39, 0xf7, 0x6e, 0x72, 0x1a, 0xd4,
	0xd6, 0xce, 0xc5, 0xd3, 0x1d, 0xa9, 0xcd, 0xb5, 0xb4, 0x72, 0x29, 0x8a, 0x5d, 0xa8, 0x8f, 0x43,
	0x7a, 0x4f, 0x11, 0x1b, 0x1a, 0xdb, 0x5e, 0xc7, 0x8b, 0xed, 0xe4, 0xdd, 0x43, 0x6a, 0xed, 0xe7,
	0x29, 0xf6, 0xa0, 0x2e, 0xb8, 0x15, 0x9f, 0x6d, 0xa7, 0x6f, 0x19, 0xb9, 0xb5, 0x8f, 0x9c, 0x56,
	0x92, 0x4f, 0xce, 0x9b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xac, 0x7c, 0x58, 0xbf, 0x84, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InstanceClient is the client API for Instance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InstanceClient interface {
	GetProperties(ctx context.Context, in *InstanceGetPropertiesRq, opts ...grpc.CallOption) (*InstanceGetPropertiesRs, error)
	SetProperties(ctx context.Context, in *InstanceSetPropertiesRq, opts ...grpc.CallOption) (*InstanceGetPropertiesRs, error)
	Subscribe(ctx context.Context, in *InstanceSubscribeRq, opts ...grpc.CallOption) (*InstanceSubscribeRs, error)
	Unsubscribe(ctx context.Context, in *InstanceSubscribeRq, opts ...grpc.CallOption) (*InstanceSubscribeRs, error)
	ListActivities(ctx context.Context, in *InstanceListActivitiesRq, opts ...grpc.CallOption) (*InstanceListActivitiesRs, error)
	ChangeState(ctx context.Context, in *InstanceChangeStateRq, opts ...grpc.CallOption) (*InstanceChangeStateRq, error)
}

type instanceClient struct {
	cc *grpc.ClientConn
}

func NewInstanceClient(cc *grpc.ClientConn) InstanceClient {
	return &instanceClient{cc}
}

func (c *instanceClient) GetProperties(ctx context.Context, in *InstanceGetPropertiesRq, opts ...grpc.CallOption) (*InstanceGetPropertiesRs, error) {
	out := new(InstanceGetPropertiesRs)
	err := c.cc.Invoke(ctx, "/grpc.Instance/GetProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceClient) SetProperties(ctx context.Context, in *InstanceSetPropertiesRq, opts ...grpc.CallOption) (*InstanceGetPropertiesRs, error) {
	out := new(InstanceGetPropertiesRs)
	err := c.cc.Invoke(ctx, "/grpc.Instance/SetProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceClient) Subscribe(ctx context.Context, in *InstanceSubscribeRq, opts ...grpc.CallOption) (*InstanceSubscribeRs, error) {
	out := new(InstanceSubscribeRs)
	err := c.cc.Invoke(ctx, "/grpc.Instance/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceClient) Unsubscribe(ctx context.Context, in *InstanceSubscribeRq, opts ...grpc.CallOption) (*InstanceSubscribeRs, error) {
	out := new(InstanceSubscribeRs)
	err := c.cc.Invoke(ctx, "/grpc.Instance/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceClient) ListActivities(ctx context.Context, in *InstanceListActivitiesRq, opts ...grpc.CallOption) (*InstanceListActivitiesRs, error) {
	out := new(InstanceListActivitiesRs)
	err := c.cc.Invoke(ctx, "/grpc.Instance/ListActivities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceClient) ChangeState(ctx context.Context, in *InstanceChangeStateRq, opts ...grpc.CallOption) (*InstanceChangeStateRq, error) {
	out := new(InstanceChangeStateRq)
	err := c.cc.Invoke(ctx, "/grpc.Instance/ChangeState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstanceServer is the server API for Instance service.
type InstanceServer interface {
	GetProperties(context.Context, *InstanceGetPropertiesRq) (*InstanceGetPropertiesRs, error)
	SetProperties(context.Context, *InstanceSetPropertiesRq) (*InstanceGetPropertiesRs, error)
	Subscribe(context.Context, *InstanceSubscribeRq) (*InstanceSubscribeRs, error)
	Unsubscribe(context.Context, *InstanceSubscribeRq) (*InstanceSubscribeRs, error)
	ListActivities(context.Context, *InstanceListActivitiesRq) (*InstanceListActivitiesRs, error)
	ChangeState(context.Context, *InstanceChangeStateRq) (*InstanceChangeStateRq, error)
}

// UnimplementedInstanceServer can be embedded to have forward compatible implementations.
type UnimplementedInstanceServer struct {
}

func (*UnimplementedInstanceServer) GetProperties(ctx context.Context, req *InstanceGetPropertiesRq) (*InstanceGetPropertiesRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProperties not implemented")
}
func (*UnimplementedInstanceServer) SetProperties(ctx context.Context, req *InstanceSetPropertiesRq) (*InstanceGetPropertiesRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProperties not implemented")
}
func (*UnimplementedInstanceServer) Subscribe(ctx context.Context, req *InstanceSubscribeRq) (*InstanceSubscribeRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedInstanceServer) Unsubscribe(ctx context.Context, req *InstanceSubscribeRq) (*InstanceSubscribeRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (*UnimplementedInstanceServer) ListActivities(ctx context.Context, req *InstanceListActivitiesRq) (*InstanceListActivitiesRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActivities not implemented")
}
func (*UnimplementedInstanceServer) ChangeState(ctx context.Context, req *InstanceChangeStateRq) (*InstanceChangeStateRq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeState not implemented")
}

func RegisterInstanceServer(s *grpc.Server, srv InstanceServer) {
	s.RegisterService(&_Instance_serviceDesc, srv)
}

func _Instance_GetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceGetPropertiesRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).GetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Instance/GetProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).GetProperties(ctx, req.(*InstanceGetPropertiesRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instance_SetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceSetPropertiesRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).SetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Instance/SetProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).SetProperties(ctx, req.(*InstanceSetPropertiesRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instance_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceSubscribeRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Instance/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).Subscribe(ctx, req.(*InstanceSubscribeRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instance_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceSubscribeRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Instance/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).Unsubscribe(ctx, req.(*InstanceSubscribeRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instance_ListActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceListActivitiesRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).ListActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Instance/ListActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).ListActivities(ctx, req.(*InstanceListActivitiesRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instance_ChangeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceChangeStateRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).ChangeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Instance/ChangeState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).ChangeState(ctx, req.(*InstanceChangeStateRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Instance_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Instance",
	HandlerType: (*InstanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProperties",
			Handler:    _Instance_GetProperties_Handler,
		},
		{
			MethodName: "SetProperties",
			Handler:    _Instance_SetProperties_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _Instance_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _Instance_Unsubscribe_Handler,
		},
		{
			MethodName: "ListActivities",
			Handler:    _Instance_ListActivities_Handler,
		},
		{
			MethodName: "ChangeState",
			Handler:    _Instance_ChangeState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "instance.proto",
}
