// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serviceRegistry.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceRegistryListDefinitionsRq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRegistryListDefinitionsRq) Reset()         { *m = ServiceRegistryListDefinitionsRq{} }
func (m *ServiceRegistryListDefinitionsRq) String() string { return proto.CompactTextString(m) }
func (*ServiceRegistryListDefinitionsRq) ProtoMessage()    {}
func (*ServiceRegistryListDefinitionsRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7640725af7f4fe3b, []int{0}
}

func (m *ServiceRegistryListDefinitionsRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRegistryListDefinitionsRq.Unmarshal(m, b)
}
func (m *ServiceRegistryListDefinitionsRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRegistryListDefinitionsRq.Marshal(b, m, deterministic)
}
func (m *ServiceRegistryListDefinitionsRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRegistryListDefinitionsRq.Merge(m, src)
}
func (m *ServiceRegistryListDefinitionsRq) XXX_Size() int {
	return xxx_messageInfo_ServiceRegistryListDefinitionsRq.Size(m)
}
func (m *ServiceRegistryListDefinitionsRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRegistryListDefinitionsRq.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRegistryListDefinitionsRq proto.InternalMessageInfo

type ServiceRegistryListDefinitionsRs struct {
	Sequence             []*ServiceRegistryListDefinitionsRsSequence `protobuf:"bytes,1,rep,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *ServiceRegistryListDefinitionsRs) Reset()         { *m = ServiceRegistryListDefinitionsRs{} }
func (m *ServiceRegistryListDefinitionsRs) String() string { return proto.CompactTextString(m) }
func (*ServiceRegistryListDefinitionsRs) ProtoMessage()    {}
func (*ServiceRegistryListDefinitionsRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7640725af7f4fe3b, []int{1}
}

func (m *ServiceRegistryListDefinitionsRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRegistryListDefinitionsRs.Unmarshal(m, b)
}
func (m *ServiceRegistryListDefinitionsRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRegistryListDefinitionsRs.Marshal(b, m, deterministic)
}
func (m *ServiceRegistryListDefinitionsRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRegistryListDefinitionsRs.Merge(m, src)
}
func (m *ServiceRegistryListDefinitionsRs) XXX_Size() int {
	return xxx_messageInfo_ServiceRegistryListDefinitionsRs.Size(m)
}
func (m *ServiceRegistryListDefinitionsRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRegistryListDefinitionsRs.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRegistryListDefinitionsRs proto.InternalMessageInfo

func (m *ServiceRegistryListDefinitionsRs) GetSequence() []*ServiceRegistryListDefinitionsRsSequence {
	if m != nil {
		return m.Sequence
	}
	return nil
}

type ServiceRegistryListDefinitionsRsSequence struct {
	DefinitionKey        string   `protobuf:"bytes,1,opt,name=DefinitionKey,proto3" json:"DefinitionKey,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRegistryListDefinitionsRsSequence) Reset() {
	*m = ServiceRegistryListDefinitionsRsSequence{}
}
func (m *ServiceRegistryListDefinitionsRsSequence) String() string { return proto.CompactTextString(m) }
func (*ServiceRegistryListDefinitionsRsSequence) ProtoMessage()    {}
func (*ServiceRegistryListDefinitionsRsSequence) Descriptor() ([]byte, []int) {
	return fileDescriptor_7640725af7f4fe3b, []int{2}
}

func (m *ServiceRegistryListDefinitionsRsSequence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRegistryListDefinitionsRsSequence.Unmarshal(m, b)
}
func (m *ServiceRegistryListDefinitionsRsSequence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRegistryListDefinitionsRsSequence.Marshal(b, m, deterministic)
}
func (m *ServiceRegistryListDefinitionsRsSequence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRegistryListDefinitionsRsSequence.Merge(m, src)
}
func (m *ServiceRegistryListDefinitionsRsSequence) XXX_Size() int {
	return xxx_messageInfo_ServiceRegistryListDefinitionsRsSequence.Size(m)
}
func (m *ServiceRegistryListDefinitionsRsSequence) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRegistryListDefinitionsRsSequence.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRegistryListDefinitionsRsSequence proto.InternalMessageInfo

func (m *ServiceRegistryListDefinitionsRsSequence) GetDefinitionKey() string {
	if m != nil {
		return m.DefinitionKey
	}
	return ""
}

func (m *ServiceRegistryListDefinitionsRsSequence) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceRegistryListDefinitionsRsSequence) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ServiceRegistryListDefinitionsRsSequence) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServiceRegistryListDefinitionsRsSequence) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ServiceRegistryNewDefinitionRq struct {
	ProcessLanguage      string   `protobuf:"bytes,1,opt,name=ProcessLanguage,proto3" json:"ProcessLanguage,omitempty"`
	Definition           string   `protobuf:"bytes,2,opt,name=Definition,proto3" json:"Definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRegistryNewDefinitionRq) Reset()         { *m = ServiceRegistryNewDefinitionRq{} }
func (m *ServiceRegistryNewDefinitionRq) String() string { return proto.CompactTextString(m) }
func (*ServiceRegistryNewDefinitionRq) ProtoMessage()    {}
func (*ServiceRegistryNewDefinitionRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7640725af7f4fe3b, []int{3}
}

func (m *ServiceRegistryNewDefinitionRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRegistryNewDefinitionRq.Unmarshal(m, b)
}
func (m *ServiceRegistryNewDefinitionRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRegistryNewDefinitionRq.Marshal(b, m, deterministic)
}
func (m *ServiceRegistryNewDefinitionRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRegistryNewDefinitionRq.Merge(m, src)
}
func (m *ServiceRegistryNewDefinitionRq) XXX_Size() int {
	return xxx_messageInfo_ServiceRegistryNewDefinitionRq.Size(m)
}
func (m *ServiceRegistryNewDefinitionRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRegistryNewDefinitionRq.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRegistryNewDefinitionRq proto.InternalMessageInfo

func (m *ServiceRegistryNewDefinitionRq) GetProcessLanguage() string {
	if m != nil {
		return m.ProcessLanguage
	}
	return ""
}

func (m *ServiceRegistryNewDefinitionRq) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

type ServiceRegistryNewDefinitionRs struct {
	Definition           string   `protobuf:"bytes,1,opt,name=Definition,proto3" json:"Definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRegistryNewDefinitionRs) Reset()         { *m = ServiceRegistryNewDefinitionRs{} }
func (m *ServiceRegistryNewDefinitionRs) String() string { return proto.CompactTextString(m) }
func (*ServiceRegistryNewDefinitionRs) ProtoMessage()    {}
func (*ServiceRegistryNewDefinitionRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7640725af7f4fe3b, []int{4}
}

func (m *ServiceRegistryNewDefinitionRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRegistryNewDefinitionRs.Unmarshal(m, b)
}
func (m *ServiceRegistryNewDefinitionRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRegistryNewDefinitionRs.Marshal(b, m, deterministic)
}
func (m *ServiceRegistryNewDefinitionRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRegistryNewDefinitionRs.Merge(m, src)
}
func (m *ServiceRegistryNewDefinitionRs) XXX_Size() int {
	return xxx_messageInfo_ServiceRegistryNewDefinitionRs.Size(m)
}
func (m *ServiceRegistryNewDefinitionRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRegistryNewDefinitionRs.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRegistryNewDefinitionRs proto.InternalMessageInfo

func (m *ServiceRegistryNewDefinitionRs) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

type ServiceRegistryGetPropertiesRq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRegistryGetPropertiesRq) Reset()         { *m = ServiceRegistryGetPropertiesRq{} }
func (m *ServiceRegistryGetPropertiesRq) String() string { return proto.CompactTextString(m) }
func (*ServiceRegistryGetPropertiesRq) ProtoMessage()    {}
func (*ServiceRegistryGetPropertiesRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7640725af7f4fe3b, []int{5}
}

func (m *ServiceRegistryGetPropertiesRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRegistryGetPropertiesRq.Unmarshal(m, b)
}
func (m *ServiceRegistryGetPropertiesRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRegistryGetPropertiesRq.Marshal(b, m, deterministic)
}
func (m *ServiceRegistryGetPropertiesRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRegistryGetPropertiesRq.Merge(m, src)
}
func (m *ServiceRegistryGetPropertiesRq) XXX_Size() int {
	return xxx_messageInfo_ServiceRegistryGetPropertiesRq.Size(m)
}
func (m *ServiceRegistryGetPropertiesRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRegistryGetPropertiesRq.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRegistryGetPropertiesRq proto.InternalMessageInfo

func (m *ServiceRegistryGetPropertiesRq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ServiceRegistryGetPropertiesRs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRegistryGetPropertiesRs) Reset()         { *m = ServiceRegistryGetPropertiesRs{} }
func (m *ServiceRegistryGetPropertiesRs) String() string { return proto.CompactTextString(m) }
func (*ServiceRegistryGetPropertiesRs) ProtoMessage()    {}
func (*ServiceRegistryGetPropertiesRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7640725af7f4fe3b, []int{6}
}

func (m *ServiceRegistryGetPropertiesRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRegistryGetPropertiesRs.Unmarshal(m, b)
}
func (m *ServiceRegistryGetPropertiesRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRegistryGetPropertiesRs.Marshal(b, m, deterministic)
}
func (m *ServiceRegistryGetPropertiesRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRegistryGetPropertiesRs.Merge(m, src)
}
func (m *ServiceRegistryGetPropertiesRs) XXX_Size() int {
	return xxx_messageInfo_ServiceRegistryGetPropertiesRs.Size(m)
}
func (m *ServiceRegistryGetPropertiesRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRegistryGetPropertiesRs.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRegistryGetPropertiesRs proto.InternalMessageInfo

func (m *ServiceRegistryGetPropertiesRs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ServiceRegistryGetPropertiesRs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceRegistryGetPropertiesRs) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ServiceRegistryGetPropertiesRs) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServiceRegistryGetPropertiesRs) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceRegistryListDefinitionsRq)(nil), "grpc.ServiceRegistryListDefinitionsRq")
	proto.RegisterType((*ServiceRegistryListDefinitionsRs)(nil), "grpc.ServiceRegistryListDefinitionsRs")
	proto.RegisterType((*ServiceRegistryListDefinitionsRsSequence)(nil), "grpc.ServiceRegistryListDefinitionsRsSequence")
	proto.RegisterType((*ServiceRegistryNewDefinitionRq)(nil), "grpc.ServiceRegistryNewDefinitionRq")
	proto.RegisterType((*ServiceRegistryNewDefinitionRs)(nil), "grpc.ServiceRegistryNewDefinitionRs")
	proto.RegisterType((*ServiceRegistryGetPropertiesRq)(nil), "grpc.ServiceRegistryGetPropertiesRq")
	proto.RegisterType((*ServiceRegistryGetPropertiesRs)(nil), "grpc.ServiceRegistryGetPropertiesRs")
}

func init() { proto.RegisterFile("serviceRegistry.proto", fileDescriptor_7640725af7f4fe3b) }

var fileDescriptor_7640725af7f4fe3b = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0x26, 0x37, 0xbd, 0xbd, 0xd7, 0x53, 0x4a, 0xe5, 0x80, 0x12, 0xba, 0x28, 0x21, 0x14, 0xc9,
	0x2a, 0x8b, 0xfa, 0x02, 0x2e, 0x0a, 0x82, 0x96, 0x52, 0x12, 0x70, 0xe3, 0x2a, 0x86, 0x63, 0x18,
	0xc1, 0xfc, 0xcc, 0x99, 0x2a, 0x7d, 0x06, 0xdf, 0xc0, 0x27, 0xf1, 0xf1, 0x24, 0x43, 0x34, 0xcd,
	0x54, 0x49, 0xdc, 0xb8, 0x9b, 0x39, 0xdf, 0xcf, 0x7c, 0x7c, 0x39, 0x04, 0x4e, 0x98, 0xe4, 0x93,
	0x48, 0x28, 0xa4, 0x54, 0xb0, 0x92, 0xbb, 0xa0, 0x90, 0xb9, 0xca, 0x71, 0x90, 0xca, 0x22, 0xf1,
	0x3c, 0x70, 0xa3, 0x36, 0xbc, 0x12, 0xac, 0x96, 0x74, 0x2f, 0x32, 0xa1, 0x44, 0x9e, 0x71, 0x58,
	0x7a, 0x59, 0x27, 0x87, 0xf1, 0x0a, 0xfe, 0x33, 0x95, 0x5b, 0xca, 0x12, 0x72, 0x2c, 0xd7, 0xf6,
	0x47, 0x8b, 0x20, 0xa8, 0x1e, 0x08, 0xba, 0x94, 0x51, 0xad, 0x0a, 0x3f, 0xf5, 0xde, 0x9b, 0x05,
	0x7e, 0x5f, 0x19, 0xce, 0x61, 0xdc, 0x00, 0xd7, 0xb4, 0x73, 0x2c, 0xd7, 0xf2, 0x8f, 0xc2, 0xf6,
	0x10, 0x11, 0x06, 0xeb, 0xf8, 0x91, 0x9c, 0x3f, 0x1a, 0xd4, 0x67, 0x74, 0x61, 0xb4, 0x24, 0x4e,
	0xa4, 0x28, 0x2a, 0x96, 0x63, 0x6b, 0x68, 0x7f, 0x84, 0x0e, 0xfc, 0xbb, 0x21, 0xc9, 0x15, 0x3a,
	0xd0, 0xe8, 0xc7, 0x15, 0x4f, 0x61, 0x18, 0xa9, 0x58, 0x6d, 0xd9, 0xf9, 0xab, 0x81, 0xfa, 0xe6,
	0x3d, 0xc0, 0xcc, 0x48, 0xbe, 0xa6, 0xe7, 0x26, 0x4a, 0x58, 0xa2, 0x0f, 0x93, 0x8d, 0xcc, 0x13,
	0x62, 0x5e, 0xc5, 0x59, 0xba, 0x8d, 0x53, 0xaa, 0x13, 0x9b, 0x63, 0x9c, 0x01, 0x34, 0xca, 0x3a,
	0xf9, 0xde, 0xc4, 0xbb, 0xe8, 0x78, 0x8b, 0x0d, 0x07, 0xeb, 0xc0, 0x61, 0x71, 0xe0, 0x70, 0x49,
	0x6a, 0x23, 0xf3, 0x82, 0xa4, 0x12, 0xc4, 0x61, 0x89, 0xc7, 0x60, 0x37, 0x9d, 0x56, 0x47, 0xef,
	0xd5, 0xea, 0x10, 0xf1, 0xa1, 0xe8, 0xb7, 0xea, 0x5f, 0xbc, 0xd8, 0x30, 0x31, 0xc2, 0x61, 0x0c,
	0x13, 0x63, 0x7b, 0xf0, 0xac, 0xd7, 0x6a, 0x96, 0xd3, 0x7e, 0x3c, 0xc6, 0x5b, 0x18, 0xb7, 0xaa,
	0xc7, 0xf9, 0x97, 0x42, 0x63, 0x15, 0xa6, 0x7d, 0x58, 0xda, 0xbc, 0x55, 0xf0, 0x37, 0xe6, 0xc6,
	0x97, 0x9b, 0xf6, 0x61, 0x69, 0xf3, 0xe8, 0xc7, 0xe6, 0xdc, 0xcb, 0xbc, 0xbc, 0x1b, 0xea, 0x1f,
	0xcd, 0xf9, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x6c, 0xbe, 0xe2, 0x81, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceRegistryClient is the client API for ServiceRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceRegistryClient interface {
	ListDefinitions(ctx context.Context, in *ServiceRegistryListDefinitionsRq, opts ...grpc.CallOption) (*ServiceRegistryListDefinitionsRs, error)
	NewDefinition(ctx context.Context, in *ServiceRegistryNewDefinitionRq, opts ...grpc.CallOption) (*ServiceRegistryNewDefinitionRs, error)
	GetProperties(ctx context.Context, in *ServiceRegistryGetPropertiesRq, opts ...grpc.CallOption) (*ServiceRegistryGetPropertiesRs, error)
	SetProperties(ctx context.Context, in *ServiceRegistryGetPropertiesRs, opts ...grpc.CallOption) (*ServiceRegistryGetPropertiesRq, error)
}

type serviceRegistryClient struct {
	cc *grpc.ClientConn
}

func NewServiceRegistryClient(cc *grpc.ClientConn) ServiceRegistryClient {
	return &serviceRegistryClient{cc}
}

func (c *serviceRegistryClient) ListDefinitions(ctx context.Context, in *ServiceRegistryListDefinitionsRq, opts ...grpc.CallOption) (*ServiceRegistryListDefinitionsRs, error) {
	out := new(ServiceRegistryListDefinitionsRs)
	err := c.cc.Invoke(ctx, "/grpc.ServiceRegistry/ListDefinitions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) NewDefinition(ctx context.Context, in *ServiceRegistryNewDefinitionRq, opts ...grpc.CallOption) (*ServiceRegistryNewDefinitionRs, error) {
	out := new(ServiceRegistryNewDefinitionRs)
	err := c.cc.Invoke(ctx, "/grpc.ServiceRegistry/NewDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) GetProperties(ctx context.Context, in *ServiceRegistryGetPropertiesRq, opts ...grpc.CallOption) (*ServiceRegistryGetPropertiesRs, error) {
	out := new(ServiceRegistryGetPropertiesRs)
	err := c.cc.Invoke(ctx, "/grpc.ServiceRegistry/GetProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) SetProperties(ctx context.Context, in *ServiceRegistryGetPropertiesRs, opts ...grpc.CallOption) (*ServiceRegistryGetPropertiesRq, error) {
	out := new(ServiceRegistryGetPropertiesRq)
	err := c.cc.Invoke(ctx, "/grpc.ServiceRegistry/SetProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceRegistryServer is the server API for ServiceRegistry service.
type ServiceRegistryServer interface {
	ListDefinitions(context.Context, *ServiceRegistryListDefinitionsRq) (*ServiceRegistryListDefinitionsRs, error)
	NewDefinition(context.Context, *ServiceRegistryNewDefinitionRq) (*ServiceRegistryNewDefinitionRs, error)
	GetProperties(context.Context, *ServiceRegistryGetPropertiesRq) (*ServiceRegistryGetPropertiesRs, error)
	SetProperties(context.Context, *ServiceRegistryGetPropertiesRs) (*ServiceRegistryGetPropertiesRq, error)
}

// UnimplementedServiceRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedServiceRegistryServer struct {
}

func (*UnimplementedServiceRegistryServer) ListDefinitions(ctx context.Context, req *ServiceRegistryListDefinitionsRq) (*ServiceRegistryListDefinitionsRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDefinitions not implemented")
}
func (*UnimplementedServiceRegistryServer) NewDefinition(ctx context.Context, req *ServiceRegistryNewDefinitionRq) (*ServiceRegistryNewDefinitionRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewDefinition not implemented")
}
func (*UnimplementedServiceRegistryServer) GetProperties(ctx context.Context, req *ServiceRegistryGetPropertiesRq) (*ServiceRegistryGetPropertiesRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProperties not implemented")
}
func (*UnimplementedServiceRegistryServer) SetProperties(ctx context.Context, req *ServiceRegistryGetPropertiesRs) (*ServiceRegistryGetPropertiesRq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProperties not implemented")
}

func RegisterServiceRegistryServer(s *grpc.Server, srv ServiceRegistryServer) {
	s.RegisterService(&_ServiceRegistry_serviceDesc, srv)
}

func _ServiceRegistry_ListDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRegistryListDefinitionsRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).ListDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ServiceRegistry/ListDefinitions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).ListDefinitions(ctx, req.(*ServiceRegistryListDefinitionsRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_NewDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRegistryNewDefinitionRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).NewDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ServiceRegistry/NewDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).NewDefinition(ctx, req.(*ServiceRegistryNewDefinitionRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_GetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRegistryGetPropertiesRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).GetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ServiceRegistry/GetProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).GetProperties(ctx, req.(*ServiceRegistryGetPropertiesRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_SetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRegistryGetPropertiesRs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).SetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ServiceRegistry/SetProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).SetProperties(ctx, req.(*ServiceRegistryGetPropertiesRs))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ServiceRegistry",
	HandlerType: (*ServiceRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDefinitions",
			Handler:    _ServiceRegistry_ListDefinitions_Handler,
		},
		{
			MethodName: "NewDefinition",
			Handler:    _ServiceRegistry_NewDefinition_Handler,
		},
		{
			MethodName: "GetProperties",
			Handler:    _ServiceRegistry_GetProperties_Handler,
		},
		{
			MethodName: "SetProperties",
			Handler:    _ServiceRegistry_SetProperties_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviceRegistry.proto",
}
